server:
   context-path: /helloboot
   port: 8081

spring:
   freemarker:
      request-context-attribute: request
      charset: UTF-8
      content-type: text/html; charset=UTF-8
      template-loader-path : classpath:/templates/
#      suffix: .ftl

#spring:
#   mvc:
#      view:
#         prefix: /WEB-INF/jsp/
#         suffix: .jsp

hp:
   core:
      dao:
         interceptor:
            expression: execution(* com.yoho.springboot.dal.*DAO.*(..))